# Generated by Django 6.1.1 on 2026-09-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank'), ('card', 'Card')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='receivables.receivable')),
            ],
        ),
    ]
